### ISSUE TITLE
Access Denied when attempting to access data dump

### ISSUE THREAD

**Issue by christian-cam** [heycarsten/lcbo-api#18]
I can't access https://s3.amazonaws.com/heycarsten/lcboapi-2018-12-17.tbz2 as linked in the Readme. Do I need to request credentials?

**Comment by heycarsten** [comment]
Shouldn’t have to, I’ll have a look soon. I have a newer one from yesterday now too, I’ll put that up.

**Comment by heycarsten** [comment]
@christian-cam I've updated the SQL dump to the last one taken on Jan 21st, should be good to go

**Comment by christian-cam** [comment]
You rock, thanks!
